title: Rosalind Guide
description: A guide for using Rosalind server shared by Ken Lau lab and Hirak Sarkar lab at Vanderbilt University.
baseurl: "/rosalind_guide"
url: "https://www.hiraksarkar.com"

theme: minima
